Repository ylozadaga/vinyls-app, pull requests merged in 2022-12, with the labels that each got.

#96 Feature/hu07 1
  app/src/main/java/com/example/vinyls/models/networkAdapter/NetworkServiceAdapter.kt
  app/src/main/java/com/example/vinyls/models/repository/AlbumRepository.kt
  app/src/main/java/com/example/vinyls/view/FragmentAlbumCreate.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuColeccionista.kt
  app/src/main/java/com/example/vinyls/viewmodels/AlbumCreateViewModel.kt
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Albumes, Sprint 3

#97 Micro optimización
  app/src/main/res/drawable/button_general.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/layout/fragment_album_list.xml
  app/src/main/res/layout/fragment_collector_list.xml
  app/src/main/res/layout/fragment_menu_coleccionista.xml
  app/src/main/res/layout/fragment_menu_inicial.xml
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/layout/fragment_musician_list.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/values/colors.xml
Labels: Sprint 3, MicroOptimizacion

#98 Ajustes pendientes
  app/src/main/java/com/example/vinyls/models/adapter/CollectorAdapter.kt
  app/src/main/java/com/example/vinyls/view/FragmentAlbumCreate.kt
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/layout/fragment_collector_detail.xml
  app/src/main/res/values/strings.xml
Labels: Tarea, Sprint 3, Test

#101 Ajustes pendientes
  app/src/main/java/com/example/vinyls/models/adapter/CollectorAdapter.kt
  app/src/main/java/com/example/vinyls/view/FragmentAlbumCreate.kt
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/layout/fragment_collector_detail.xml
  app/src/main/res/values/strings.xml
Labels: Albumes, Sprint 3
