Repository ylozadaga/vinyls-app, pull requests merged in 2022-11, with the labels that each got.

#75 Feature/hu01 09
  app/src/main/java/com/example/vinyls/view/FragmentAlbumList.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuColeccionista.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuInicial.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuVisitante.kt
  app/src/main/res/drawable/button_general.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_album_list.xml
  app/src/main/res/layout/fragment_menu_coleccionista.xml
  app/src/main/res/layout/fragment_menu_inicial.xml
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Albumes, Sprint 1

#76 Feature/hu01_09
  app/build.gradle
  app/src/main/java/com/example/vinyls/models/Musician.kt
  app/src/main/java/com/example/vinyls/models/MusicianAdapter.kt
  app/src/main/java/com/example/vinyls/models/NetworkServiceAdapter.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuVisitante.kt
  app/src/main/java/com/example/vinyls/view/FragmentMusicianList.kt
  app/src/main/java/com/example/vinyls/viewmodels/MusicianListViewModel.kt
  app/src/main/res/layout/fragment_musician_list.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 1

#77 Se agrega la HU05
  app/src/main/java/com/example/vinyls/models/Collector.kt
  app/src/main/java/com/example/vinyls/models/CollectorAdapter.kt
  app/src/main/java/com/example/vinyls/models/NetworkServiceAdapter.kt
  app/src/main/java/com/example/vinyls/view/FragmentCollectorList.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuVisitante.kt
  app/src/main/java/com/example/vinyls/viewmodels/CollectorListViewModel.kt
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/layout/fragment_collector_list.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#78 Feature/hu02
  app/src/main/java/com/example/vinyls/models/AlbumsAdapter.kt
  app/src/main/java/com/example/vinyls/view/FragmentAlbumDetail.kt
  app/src/main/java/com/example/vinyls/view/FragmentAlbumList.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuColeccionista.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuInicial.kt
  app/src/main/java/com/example/vinyls/view/FragmentMenuVisitante.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/layout/fragment_album_list.xml
  app/src/main/res/layout/fragment_menu_coleccionista.xml
  app/src/main/res/layout/fragment_menu_inicial.xml
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Albumes

#79 HU03: Consultar listado de artistas (Detalle)
  app/src/main/res/drawable-v24/singer.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/layout/fragment_album_list.xml
  app/src/main/res/layout/fragment_collector_list.xml
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/layout/fragment_musician_list.xml
  app/src/main/res/layout/musician_item.xml
Labels: Artistas, Sprint 2

#82 Revert "Solución problemas de merge"
  app/src/main/java/com/example/vinyls/view/FragmentMenuVisitante.kt
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/musician_item.xml
Labels: Tarea

#87 Images
  app/build.gradle
  app/src/main/java/com/example/vinyls/models/AlbumsAdapter.kt
  app/src/main/java/com/example/vinyls/models/MusicianAdapter.kt
  app/src/main/res/drawable-v24/ic_broken_image.xml
  app/src/main/res/drawable-v24/loading_animation.xml
  app/src/main/res/drawable-v24/loading_img.xml
  app/src/main/res/layout/musician_item.xml
  gradle.properties
Labels: MicroOptimizacion

#88 Micro optimizacion
  app/build.gradle
  app/src/main/java/com/example/vinyls/models/AlbumsAdapter.kt
  app/src/main/java/com/example/vinyls/models/MusicianAdapter.kt
  app/src/main/res/drawable-v24/ic_broken_image.xml
  app/src/main/res/drawable-v24/loading_animation.xml
  app/src/main/res/drawable-v24/loading_img.xml
  app/src/main/res/drawable-v24/singer.png
  app/src/main/res/drawable/album.png
  app/src/main/res/drawable/albumes.xml
  app/src/main/res/drawable/arrow.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/fragment_musician_detail.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/values/colors.xml
  gradle.properties
Labels: MicroOptimizacion

#89 Test HU Sprint 1 y 2 funcionando
  app/build.gradle
  app/src/androidTest/java/com/example/vinyls/navigation/NavigationFragmentAlbumsList.kt
  app/src/androidTest/java/com/example/vinyls/navigation/NavigationFragmentMenuColeccionista.kt
  app/src/androidTest/java/com/example/vinyls/navigation/NavigationFragmentMenuInicial.kt
  app/src/androidTest/java/com/example/vinyls/navigation/NavigationFragmentMenuVisitante.kt
  app/src/androidTest/java/com/example/vinyls/navigation/NavigationFragmentMusicianList.kt
  app/src/androidTest/java/com/example/vinyls/view/MainActivityTest.kt
  app/src/main/java/com/example/vinyls/view/FragmentMusicianList.kt
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/layout/fragment_musician_list.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Sprint 2, Test

#92 Alistamiento Develop enviroment - Sprint 3
  README.md
  app/build.gradle
  app/src/main/java/com/example/vinyls/models/AlbumRepository.kt
  app/src/main/java/com/example/vinyls/models/adapter/AlbumsAdapter.kt
  app/src/main/java/com/example/vinyls/models/adapter/CollectorAdapter.kt
  app/src/main/java/com/example/vinyls/models/adapter/MusicianAdapter.kt
  app/src/main/java/com/example/vinyls/models/networkAdapter/NetworkServiceAdapter.kt
  app/src/main/java/com/example/vinyls/models/repository/AlbumRepository.kt
  app/src/main/java/com/example/vinyls/models/repository/CollectorRepository.kt
  app/src/main/java/com/example/vinyls/models/repository/MusicianRepository.kt
  app/src/main/java/com/example/vinyls/view/FragmentAlbumList.kt
  app/src/main/java/com/example/vinyls/view/FragmentCollectorList.kt
  app/src/main/java/com/example/vinyls/view/FragmentMusicianList.kt
  app/src/main/java/com/example/vinyls/viewmodels/AlbumListViewModel.kt
  app/src/main/java/com/example/vinyls/viewmodels/CollectorListViewModel.kt
  app/src/main/java/com/example/vinyls/viewmodels/MusicianListViewModel.kt
  build.gradle
Labels: Sprint 3

#93 Ajustes realizados de accesibilidad.
  app/src/main/res/drawable/button_general.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/layout/fragment_menu_coleccionista.xml
  app/src/main/res/layout/fragment_menu_inicial.xml
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 3

#94 Develop
  app/src/main/res/drawable/button_general.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/layout/fragment_menu_coleccionista.xml
  app/src/main/res/layout/fragment_menu_inicial.xml
  app/src/main/res/layout/fragment_menu_visitante.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 3, Accesabilidad
